import { Tournament, GlobalLeaderboardEntry } from './tournamentTypes';

const ONE_DAY = 24 * 60 * 60 * 1000;
const now = Date.now();
const dailyEnd = new Date().setHours(23, 59, 59, 999);
const weekendEnd = now + (3 * ONE_DAY);
const weeklyEnd = now + (5 * ONE_DAY);

export const DEFAULT_FALLBACK_TOURNAMENTS: Tournament[] = [
  {
    id: 'spring-meadow-cup',
    title: 'Spring Meadow Cup',
    subtitle: 'Novice Championship Arena',
    badge: 'ROOKIE OPEN',
    icon: '🌱',
    gradient: 'from-emerald-500 via-green-500 to-teal-600',
    bannerBorder: 'border-emerald-300',
    bgZoneId: 'bg-0',
    worldNumber: 1,
    worldName: 'Spring Meadow',
    requiredLevel: 1,
    seed: 104291,
    blockCount: 40,
    speedMultiplier: 1.0,
    boomChance: 0.2,
    modifierDesc: 'Open to all builders! Standard speed and gentle drops.',
    startTime: now - ONE_DAY,
    endTime: dailyEnd,
    prizes: {
      first: { coins: 2000, trophy: 'gold', title: 'Meadow Master' },
      second: { coins: 1000, trophy: 'silver', title: 'Meadow Runner-Up' },
      third: { coins: 500, trophy: 'bronze', title: 'Meadow Ace' },
      top10: { coins: 250 },
      top50: { coins: 100 },
    },
    totalParticipants: 245,
    entries: [
      { id: 'f-0', playerId: 'bot-0', playerName: 'VortexBuilder', country: '🇺🇸', avatar: '🧑‍🚀', score: 2427, blocksBuilt: 74, maxCombo: 30, timestamp: now - 3600000 },
      { id: 'f-1', playerId: 'bot-1', playerName: 'NeonSamurai', country: '🇯🇵', avatar: '🤖', score: 2337, blocksBuilt: 71, maxCombo: 28, timestamp: now - 7200000 },
      { id: 'f-2', playerId: 'bot-2', playerName: 'KaiserStack', country: '🇩🇪', avatar: '🤺', score: 2234, blocksBuilt: 68, maxCombo: 26, timestamp: now - 10800000 },
      { id: 'f-3', playerId: 'bot-3', playerName: 'SambaStriker', country: '🇧🇷', avatar: '🦀', score: 2068, blocksBuilt: 64, maxCombo: 25, timestamp: now - 14400000 },
      { id: 'f-4', playerId: 'bot-4', playerName: 'LondonEye', country: '🇬🇧', avatar: '🦊', score: 1977, blocksBuilt: 61, maxCombo: 23, timestamp: now - 18000000 },
    ],
  },
  {
    id: 'lunar-trials',
    title: 'Lunar Gravity Trials',
    subtitle: 'Low-Gravity Orbital Gauntlet',
    badge: 'WORLD 5 EXCLUSIVE',
    icon: '🧑‍🚀',
    gradient: 'from-slate-700 via-indigo-800 to-blue-900',
    bannerBorder: 'border-indigo-300',
    bgZoneId: 'bg-4',
    worldNumber: 5,
    worldName: 'Moon',
    requiredLevel: 41,
    seed: 554312,
    blockCount: 60,
    speedMultiplier: 1.15,
    boomChance: 0.25,
    modifierDesc: 'Floaty swinging crane with slippery timing. World 5 required.',
    startTime: now - 2 * ONE_DAY,
    endTime: weekendEnd,
    prizes: {
      first: { coins: 3500, trophy: 'gold', title: 'Lunar Pioneer' },
      second: { coins: 1800, trophy: 'silver', title: 'Cosmic Pilot' },
      third: { coins: 900, trophy: 'bronze', title: 'Astral Walker' },
      top10: { coins: 400 },
      top50: { coins: 150 },
    },
    totalParticipants: 354,
    entries: [
      { id: 'f-10', playerId: 'bot-0', playerName: 'VortexBuilder', country: '🇺🇸', avatar: '🧑‍🚀', score: 3380, blocksBuilt: 98, maxCombo: 30, timestamp: now - 3600000 },
      { id: 'f-11', playerId: 'bot-1', playerName: 'NeonSamurai', country: '🇯🇵', avatar: '🤖', score: 3240, blocksBuilt: 94, maxCombo: 28, timestamp: now - 7200000 },
      { id: 'f-12', playerId: 'bot-2', playerName: 'KaiserStack', country: '🇩🇪', avatar: '🤺', score: 3105, blocksBuilt: 90, maxCombo: 27, timestamp: now - 10800000 },
    ],
  },
  {
    id: 'daily-blitz',
    title: 'Meteor Blitz Cup',
    subtitle: 'Fast 24-Hour Reflex Duel',
    badge: 'WORLD 8 EXCLUSIVE',
    icon: '⚡',
    gradient: 'from-rose-500 via-red-500 to-amber-500',
    bannerBorder: 'border-red-300',
    bgZoneId: 'bg-7',
    worldNumber: 8,
    worldName: 'Volcano',
    requiredLevel: 71,
    seed: 142091,
    blockCount: 50,
    speedMultiplier: 1.35,
    boomChance: 0.35,
    modifierDesc: 'Hyper speed with dense bomb hazards! World 8 required.',
    startTime: now - 10 * 3600 * 1000,
    endTime: dailyEnd,
    prizes: {
      first: { coins: 4000, trophy: 'gold', title: 'Blitz King' },
      second: { coins: 2000, trophy: 'silver', title: 'Blitz Ace' },
      third: { coins: 1000, trophy: 'bronze', title: 'Blitz Runner-Up' },
      top10: { coins: 400 },
      top50: { coins: 150 },
    },
    totalParticipants: 312,
    entries: [
      { id: 'f-20', playerId: 'bot-0', playerName: 'VortexBuilder', country: '🇺🇸', avatar: '🧑‍🚀', score: 2920, blocksBuilt: 86, maxCombo: 30, timestamp: now - 3600000 },
      { id: 'f-21', playerId: 'bot-1', playerName: 'NeonSamurai', country: '🇯🇵', avatar: '🤖', score: 2780, blocksBuilt: 82, maxCombo: 28, timestamp: now - 7200000 },
      { id: 'f-22', playerId: 'bot-2', playerName: 'KaiserStack', country: '🇩🇪', avatar: '🤺', score: 2650, blocksBuilt: 79, maxCombo: 26, timestamp: now - 10800000 },
    ],
  },
  {
    id: 'weekly-grand-prix',
    title: 'Skyline Grand Prix',
    subtitle: 'Week 38 Championship Arena',
    badge: 'WORLD 14 MAJOR',
    icon: '🏆',
    gradient: 'from-amber-500 via-yellow-500 to-orange-500',
    bannerBorder: 'border-yellow-300',
    bgZoneId: 'bg-13',
    worldNumber: 14,
    worldName: 'Golden Legend',
    requiredLevel: 131,
    seed: 884920,
    blockCount: 100,
    speedMultiplier: 1.15,
    boomChance: 0.28,
    modifierDesc: 'High stakes 100-block gauntlet! 2x Combo Multiplier. World 14 required.',
    startTime: now - 3 * ONE_DAY,
    endTime: weeklyEnd,
    prizes: {
      first: { coins: 5000, trophy: 'gold', title: 'Grand Champion' },
      second: { coins: 2500, trophy: 'silver', title: 'Grand Finalist' },
      third: { coins: 1200, trophy: 'bronze', title: 'Podium Master' },
      top10: { coins: 500 },
      top50: { coins: 200 },
    },
    totalParticipants: 429,
    entries: [
      { id: 'f-30', playerId: 'bot-0', playerName: 'VortexBuilder', country: '🇺🇸', avatar: '🧑‍🚀', score: 4850, blocksBuilt: 143, maxCombo: 30, timestamp: now - 3600000 },
      { id: 'f-31', playerId: 'bot-1', playerName: 'NeonSamurai', country: '🇯🇵', avatar: '🤖', score: 4680, blocksBuilt: 138, maxCombo: 28, timestamp: now - 7200000 },
      { id: 'f-32', playerId: 'bot-2', playerName: 'KaiserStack', country: '🇩🇪', avatar: '🤺', score: 4520, blocksBuilt: 134, maxCombo: 27, timestamp: now - 10800000 },
    ],
  },
  {
    id: 'cyber-overdrive',
    title: 'Cyber Circuit Rush',
    subtitle: 'Neon Mirage Gauntlet',
    badge: 'WORLD 15 MASTER',
    icon: '🤖',
    gradient: 'from-cyan-500 via-blue-600 to-purple-600',
    bannerBorder: 'border-cyan-300',
    bgZoneId: 'bg-14',
    worldNumber: 15,
    worldName: 'Cyberpunk',
    requiredLevel: 141,
    seed: 991244,
    blockCount: 75,
    speedMultiplier: 1.25,
    boomChance: 0.3,
    modifierDesc: 'Deceptive ghost & blinking blocks! World 15 required.',
    startTime: now - ONE_DAY,
    endTime: weekendEnd,
    prizes: {
      first: { coins: 4500, trophy: 'gold', title: 'Neon Legend' },
      second: { coins: 2200, trophy: 'silver', title: 'Cyber Master' },
      third: { coins: 1100, trophy: 'bronze', title: 'Glitch Hunter' },
      top10: { coins: 450 },
      top50: { coins: 180 },
    },
    totalParticipants: 279,
    entries: [
      { id: 'f-40', playerId: 'bot-0', playerName: 'VortexBuilder', country: '🇺🇸', avatar: '🧑‍🚀', score: 3650, blocksBuilt: 109, maxCombo: 30, timestamp: now - 3600000 },
      { id: 'f-41', playerId: 'bot-1', playerName: 'NeonSamurai', country: '🇯🇵', avatar: '🤖', score: 3490, blocksBuilt: 104, maxCombo: 28, timestamp: now - 7200000 },
      { id: 'f-42', playerId: 'bot-2', playerName: 'KaiserStack', country: '🇩🇪', avatar: '🤺', score: 3320, blocksBuilt: 100, maxCombo: 27, timestamp: now - 10800000 },
    ],
  },
];

export const DEFAULT_FALLBACK_LEADERBOARD: GlobalLeaderboardEntry[] = [
  { id: 'glb-0', playerId: 'bot-0', playerName: 'VortexBuilder', avatar: '🧑‍🚀', country: '🇺🇸', score: 2450, secondaryStat: 'Streak x28', timestamp: now - 3600000 },
  { id: 'glb-1', playerId: 'bot-1', playerName: 'NeonSamurai', avatar: '🤖', country: '🇯🇵', score: 2320, secondaryStat: 'Streak x26', timestamp: now - 7200000 },
  { id: 'glb-2', playerId: 'bot-2', playerName: 'KaiserStack', avatar: '🤺', country: '🇩🇪', score: 2190, secondaryStat: 'Streak x25', timestamp: now - 10800000 },
  { id: 'glb-3', playerId: 'bot-3', playerName: 'SambaStriker', avatar: '🦀', country: '🇧🇷', score: 2040, secondaryStat: 'Streak x24', timestamp: now - 14400000 },
  { id: 'glb-4', playerId: 'bot-4', playerName: 'LondonEye', avatar: '🦊', country: '🇬🇧', score: 1920, secondaryStat: 'Streak x22', timestamp: now - 18000000 },
  { id: 'glb-5', playerId: 'bot-5', playerName: 'SeoulSurfer', avatar: '🐧', country: '🇰🇷', score: 1810, secondaryStat: 'Streak x21', timestamp: now - 21600000 },
  { id: 'glb-6', playerId: 'bot-6', playerName: 'NordicRune', avatar: '🌋', country: '🇸🇪', score: 1720, secondaryStat: 'Streak x20', timestamp: now - 25200000 },
  { id: 'glb-7', playerId: 'bot-7', playerName: 'MapleDrop', avatar: '🍂', country: '🇨🇦', score: 1640, secondaryStat: 'Streak x19', timestamp: now - 28800000 },
  { id: 'glb-8', playerId: 'bot-8', playerName: 'TajMaster', avatar: '🗿', country: '🇮🇳', score: 1550, secondaryStat: 'Streak x18', timestamp: now - 32400000 },
  { id: 'glb-9', playerId: 'bot-9', playerName: 'AussieBoomer', avatar: '🛻', country: '🇦🇺', score: 1470, secondaryStat: 'Streak x17', timestamp: now - 36000000 },
];

export const DEFAULT_FALLBACK_TOURNAMENT_LEADERBOARD: GlobalLeaderboardEntry[] = [
  { id: 'glt-0', playerId: 'bot-0', playerName: 'VortexBuilder', avatar: '🧑‍🚀', country: '🇺🇸', score: 5420, secondaryStat: 'Grand Prix • Combo x32', timestamp: now - 3600000 },
  { id: 'glt-1', playerId: 'bot-1', playerName: 'NeonSamurai', avatar: '🤖', country: '🇯🇵', score: 5180, secondaryStat: 'Grand Prix • Combo x30', timestamp: now - 7200000 },
  { id: 'glt-2', playerId: 'bot-2', playerName: 'KaiserStack', avatar: '🤺', country: '🇩🇪', score: 4890, secondaryStat: 'Lunar Trials • Combo x28', timestamp: now - 10800000 },
  { id: 'glt-3', playerId: 'bot-3', playerName: 'PixelGhost', avatar: '🛸', country: '🇫🇷', score: 4620, secondaryStat: 'Grand Prix • Combo x27', timestamp: now - 14400000 },
  { id: 'glt-4', playerId: 'bot-4', playerName: 'SambaStriker', avatar: '🦀', country: '🇧🇷', score: 4350, secondaryStat: 'Meteor Blitz • Combo x25', timestamp: now - 18000000 },
  { id: 'glt-5', playerId: 'bot-5', playerName: 'LondonEye', avatar: '🦊', country: '🇬🇧', score: 4100, secondaryStat: 'Lunar Trials • Combo x24', timestamp: now - 21600000 },
  { id: 'glt-6', playerId: 'bot-6', playerName: 'SeoulSurfer', avatar: '🐧', country: '🇰🇷', score: 3880, secondaryStat: 'Spring Meadow • Combo x23', timestamp: now - 25200000 },
  { id: 'glt-7', playerId: 'bot-7', playerName: 'DiamondHands', avatar: '💎', country: '🇸🇬', score: 3670, secondaryStat: 'Cyber Circuit • Combo x22', timestamp: now - 28800000 },
  { id: 'glt-8', playerId: 'bot-8', playerName: 'NordicRune', avatar: '🌋', country: '🇸🇪', score: 3490, secondaryStat: 'Meteor Blitz • Combo x21', timestamp: now - 32400000 },
  { id: 'glt-9', playerId: 'bot-9', playerName: 'GoldenCrown', avatar: '🪙', country: '🇮🇹', score: 3280, secondaryStat: 'Grand Prix • Combo x20', timestamp: now - 36000000 },
];
